### PR TITLE
IntroButton customization, docs, linting

### PR DESCRIPTION
**Pull request by EnduringBeta**
This PR is my effort to resolve my suggestions #23 and #24.

I added new parameters for `IntroButton` for additional customization.

I added documentation to many methods and properties of `Intro` and `IntroStepBuilder` especially that were missing. Notably I wish they were there when I was getting started with this package. I also updated some language as a grammar and punctuation nerd.

I made a pass on `README.md`, fixing some of what Android Studio complained about and updating language where I found it confusing.

Change anything you want; I'm just trying to help. I don't have much more energy than what I've done, but I can respond to critique if needed. You can also reject this.

I don't know what testing process you do to confirm this is stable. I added a few simple tests since there were none, but they don't prove much. I ran this branch, went through the examples, and everything looked fine. The very first time I loaded the first demo page, however, the guides didn't show. I'm not sure if that's something I affected.

### CODE REVIEW

**Comment by hellohejinyu** [comment]
This package was originally just a small feature in a work project. One day, I found that there was no similar package in the Flutter ecosystem, so I extracted this part and open sourced it. Therefore, the code quality itself and the test code are missing. As you can see, I am the only one dealing with issues in this package, so I usually only respond to some bugs and other important things. Thank you for carefully handling all the code comments, documents and other details, and adding test code for it.
I noticed that your branch is still adjusting and adding new code recently. If you are ready, can you let me know? Thank you.

**Comment by EnduringBeta** [comment]
I'm done. 👍

I updated the `Intro` doc once more after your comment about `onWidgetLoad`. In there I mention `Future.delayed`, because I think they may still be needed. If I'm wrong, feel free to correct or change anything.

Thank you for publishing this package. I totally understand why it is the way it is. It is helpful to many people.

**Comment by hellohejinyu** [comment]
Thanks for your help, I've merged the code. There are two things I need to tweak. The first issue is that we have to use `Future.delayed` to get the package working properly, which might be a bug. Could you provide me with a minimal reproducible demo? Ideally, we shouldn't need to use `Future.delayed`.

The second issue is about the changes to `IntroButton`. My original intention was to encourage everyone to implement their own custom intro pages, so I overlooked the default intro style. Since we're adjusting `IntroButton`, we might as well expose all the style properties of the button. This would give users more flexibility and reduce the limitations of using the default style. So, I'll make a few adjustments in this area.

Thanks again for your help.❤️

**Comment by EnduringBeta** [comment]
I agree with more `IntroButton` changes. I made limited changes because it's not my repo, but yes more customization is good. I'll look at the `Future.delayed` thing in issue #23

**Pull request merged**
